name: CI

on:
  push:
    branches: [main, mahdi]
  pull_request:
    branches: [main, mahdi]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install package and dev deps
        run: |
          pip install -e ".[dev,mlops,serving,monitoring]"
      - name: Ruff
        run: ruff check src tests
      - name: Pytest
        run: pytest -q
